### PR TITLE
added a warning about the size of the profile picture to be uploaded

### LINKED ISSUE #130: the profile picture does not get updated or even added for the first time
**Describe the bug**
inside the profile a user cannot cannot change their profile picture

**To Reproduce**
1. Go to 'your profile'
2. Click on 'change profile picture'
3. 'select a profile picture'
4. the profile picture does not get changed

**Expected behavior**
the profile picture should have been updated.

**Additional context**
on it

### PR DESCRIPTION
**Pull request by carpecodeum**
# Description

added a detailed warning to allow users to check the size of the images they are uploading before uploading.

Fixes #130 

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] this was tested by uploading different sized images both graeter and lesser than 101kb

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by carpecodeum** [comment]
@Tushar19varshney please review

**Comment by carpecodeum** [comment]
@ivantha @Tushar19varshney please review

**Comment by ivantha** [comment]
Please rebase this

**Comment by UdeshUK** [comment]
Duplicate of #331

**Pull request closed without merging**
