### PR TITLE
Added Image Compression Feature

### PR DESCRIPTION
**Pull request by ShreyAmbesh**
# Description

The image size of the uploaded image is large. It can be compressed and then uploaded.
Which will increase the upload speed without much loss in quality.
I have used [flutter_image_compress](https://pub.dev/packages/flutter_image_compress) package to compress the image. I had to also use [path_provider](https://pub.dev/packages/path_provider) package.
The user is given an option to either upload with compression or without compression.

Fixes [#345](https://github.com/scorelab/LabelLab/issues/345)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Once the user selects the image he/she gets an alert dialog to choose whether to upload the image with or without compression.

- [x] Tested uploading with and without compression

**Test Configuration**:

- Firmware version:  Flutter 1.12.13+hotfix.8
- Hardware:
- Toolchain:
- SDK: 28

Also, include screenshots of the app for the verification and reviewing purposes.
photo_2020-03-12_00-48-23

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by UdeshUK** [comment]
@ShreyAmbesh this is a great feature for the classification feature since upload time is dropped but it would be a better user experience if the user is given a checkbox or an option before uploading the image instead of showing a dialog.

**Comment by ShreyAmbesh** [comment]
I think instead of the image getting uploaded automatically once it is selected maybe an upload button and the compression option in that page will be a better option as the user will get to select it before uploading and once he selects or deselects the compression option he can click the upload button to start the upload.
@UdeshUK  It will be great if you can give me suggestions on this idea.

**Comment by UdeshUK** [comment]
@ShreyAmbesh Yes, this would be a better implementation. Can you work on it?

**Comment by ShreyAmbesh** [comment]
Okay, I will implement it and push the code by today.

**Comment by ShreyAmbesh** [comment]
@UdeshUK I have made the required changes. Kindly go through them.


photo_2020-03-13_15-27-11

**Pull request merged**
