### PR TITLE
Project Details Component UI responsiveness and fixes

### PR DESCRIPTION
**Pull request by DonOmalVindula**
# Description

This contains various UI fixes in the Project Details Component including alignments, mobile responsiveness and spacing.

Fixes
issue #379 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Create a new project and go to the project details page by clicking on the relevant card. Using Chrome Dev Tools adjust for different views and tested for responsiveness and UI issues.

Also, include screenshots of app for the verification and reviewing purpose.

UI fixes are listed below. The screenshots before fixes (with issues) can be found on issue #379 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Tushar19varshney** [comment]
@DonOmalVindula Rebase the PR!

**Comment by Tushar19varshney** [comment]
@DonOmalVindula Rebase the PR!

**Comment by ivantha** [comment]
@DonOmalVindula Can you rebase this please?

**Comment by DonOmalVindula** [comment]
> @DonOmalVindula Can you rebase this please?

I have rebased it with master and pushed it. Can you please check if everything is in order?

**Pull request closed without merging**
