### PR TITLE
Update: ER structure and relationships

### PR DESCRIPTION
**Pull request by carpecodeum**
# Description
Changes in the table names and the column names

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Test Configuration**:
Design

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

Also, include screenshots of app for the verification and reviewing purpose.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by carpecodeum** [comment]
I have kept the project to project_members relationship as one to many so that if and when we need to get the project members inside a particular project we can easily query out using the project members table.

**Comment by carpecodeum** [comment]
@ivantha i think that for querying out all the project members in a project it is better to have project members connected to the project model also labels no longer have a relationship with the image as i thought it was better to have a relationship with the project rather than a particular image. These are open for discussions and deliberations and once we reach a conclusive discussion I'm going to change it :).

**Comment by laksh22** [comment]
@ivantha Yes the consensus was that the versions table is not needed as of now

**Comment by ivantha** [comment]
> @ivantha i think that for querying out all the project members in a project it is better to have project members connected to the project model also labels no longer have a relationship with the image as i thought it was better to have a relationship with the project rather than a particular image. These are open for discussions and deliberations and once we reach a conclusive discussion I'm going to change it :).

IMO that is not necessary for a project like this where db query performance is not critical.

**Comment by carpecodeum** [comment]
> > @ivantha i think that for querying out all the project members in a project it is better to have project members connected to the project model also labels no longer have a relationship with the image as i thought it was better to have a relationship with the project rather than a particular image. These are open for discussions and deliberations and once we reach a conclusive discussion I'm going to change it :).
> 
> IMO that is not necessary for a project like this where db query performance is not critical.

okay i will change it

**Comment by carpecodeum** [comment]
@ivantha is this alright now?

**Comment by laksh22** [comment]
@carpecodeum I think the version table has to be removed as well

**Comment by carpecodeum** [comment]
@cazci can you please confirm if the version table is not required?

**Comment by cazci** [comment]
Shall we update the table name from version -> model as we discussed. May I explain a bit more about the necessity of that table, I guess I wasn't quite clear on the call. 

The use case is a user can select multiple images inside a project and train them. This may occur multiple times with different sets of images. In the end, the user should be able to view the previous training instances (can name them as "version 1", "version 2", ... ). 

I had a discussion with @ivantha on this matter, and he suggested a better way by creating image subgroups in a project before training. So a user can create a group of images, name them and then feed them to training. I'll start a discussion in gitter, so that everyone can participate there. Otherwise, this thread may get unnecessarily long.

**Comment by cazci** [comment]
Shall we update the table name from version -> model as discussed. May I explain a bit more about the necessity of that table, I guess I wasn't quite clear on the call. 

The use case is a user can select multiple images inside a project and train them. This may occur multiple times with different sets of images. In the end, the user should be able to view the previous training instances (can name them as "version 1", "version 2", ... )

I guess it's better if there's a feature to create image subgroups in a project before training. So a user can create a group of images, name them, and then feed them to training. I'll start a discussion in gitter, so that everyone can participate there. Otherwise, this thread may get unnecessarily long.

**Comment by carpecodeum** [comment]
@ivantha @UdeshUK @Tushar19varshney We have all integrated the Web, Mobile and ML database structure.. please review.

**Pull request merged**
