### PR TITLE
Add databases and initial migrations files

### PR DESCRIPTION
**Pull request by carpecodeum**
Add databases for labels users labeldata projects images team and projectmembers and create its migrations file.

Fixes #424 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Test Configuration**:

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

Also, include screenshots of app for the verification and reviewing purpose.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by carpecodeum** [comment]
Ref #429 on the basis on changes suggested in the following discussion

**Comment by carpecodeum** [comment]
@ivantha @udesh @Tushar19varshney Please review this

**Comment by Tushar19varshney** [comment]
@carpecodeum Label can be a independent entity, so we don't have to attach project_id with it. We can attach a many to many keys in project model, and if needed you can create a through model. Any suggestions ?

**Comment by carpecodeum** [comment]
> @carpecodeum Label can be a independent entity, so we don't have to attach project_id with it. We can attach a many to many key in project model, and if needed you can create a through model. Any suggestions ?

I thought labels were subject to the kind of project we were working on like a certain project would be used to label only a particular type of object in that sense any of the labels in any other projects would hardly be similar.

**Comment by Tushar19varshney** [comment]
> > @carpecodeum Label can be a independent entity, so we don't have to attach project_id with it. We can attach a many to many key in project model, and if needed you can create a through model. Any suggestions ?
> 
> I thought labels were subject to the kind of project we were working on like a certain project would be used to label only a particular type of object in that sense any of the labels in any other projects would hardly be similar.

Like many of the labels can be common, if it is, then we don't want user to recreate that label once again for only that project. I think we need to discuss this upon with other members @ivantha @UdeshUK

**Comment by carpecodeum** [comment]
@ivantha @udesh please give your thoughts on this i think we should finalize this so that we can move on to creating apis.

**Comment by ivantha** [comment]
Yes, labels can be similar. But let's keep the labels of projects separated.

**Comment by carpecodeum** [comment]
> Yes, labels can be similar. But let's keep the labels of projects separated.

Yes they are separate only! :)

**Pull request closed without merging**
