### PR TITLE
delete images from server as well

### LINKED ISSUE #176: Images are not deleted from the server only deleted from the database
**Describe the bug**
images when deleted from the database are not deleted from the server

**To Reproduce**
1. Go to 'project images.'
2. Click on 'delete image'
3. open uploads folder
4. see persisted image

**Expected behavior**
the image should have been deleted from the server as well

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS

**Additional context**

### PR DESCRIPTION
**Pull request by carpecodeum**
# Description

delete images from server as well when images are deleted from db

Fixes #176 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

tested by uploading and deleting images

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by carpecodeum** [comment]
@ivantha please review

**Comment by carpecodeum** [comment]
> Nice work 👍 , Rebase commits. I'll merge this then.

Sure I will do this right now.

**Comment by carpecodeum** [comment]
@UdeshUK please review

**Comment by UdeshUK** [comment]
Squash commits into a single one

**Pull request merged**
