### PR TITLE
Add tests for frontend

### PR DESCRIPTION
**Pull request by carpecodeum**
# Description

Add tests for frontend:
1. Add tests for auth, register and project reducers.
2. Add testUtils.js file and tests for login and dashboard components.

Fixes #424 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Annotation 2020-06-27 183239

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Tushar19varshney** [comment]
@carpecodeum Actually, you can do one more thing - add configurations for testing in travis too, so that everyone can have check on the tests running and failing.

**Comment by carpecodeum** [comment]
> @carpecodeum Actually, you can do one more thing - add configurations for testing in travis too, so that everyone can have check on the tests running and failing.

Done!

**Comment by ivantha** [comment]
@hiranthaR @Tushar19varshney Can we merge this?

**Comment by Tushar19varshney** [comment]
> @hiranthaR @Tushar19varshney Can we merge this?

@ivantha Yes we can :+1:

**Comment by UdeshUK** [comment]
@carpecodeum some client-side tests are failing. Can you check [https://travis-ci.com/github/scorelab/LabelLab/builds/176459556](https://travis-ci.com/github/scorelab/LabelLab/builds/176459556)

**Comment by carpecodeum** [comment]
> @carpecodeum some client-side tests are failing.
> 
> ```
>  [500] - FAIL  src/__tests__/reducers/projectReducers.test.js
>  [643] - FAIL  src/__tests__/reducers/authReducer.test.js
> ```
> 
> Can you check https://travis-ci.com/github/scorelab/LabelLab/builds/176459556

I have fixed this in #489

**Pull request merged**
