### PR TITLE
add unit tests for user route and create a sample info file

### PR DESCRIPTION
**Pull request by carpecodeum**
# Description

Tests for User route added
Fixes # (issue)152

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Screenshot 2019-12-27 at 3 00 26 AM

- [ ] Test A
- [ ] Test B

Also, include screenshots of app for the verification and reviewing purpose.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by carpecodeum** [comment]
@Tushar19varshney please review

**Comment by carpecodeum** [comment]
@ivantha @Tushar19varshney please review

**Comment by carpecodeum** [comment]
> @carpecodeum Make sure language styles are followed and remove unrelated files from the PR (eg: images, etc).

I am sorry but i dont understand what do you mean by language styles? Could you please elaborate?

**Comment by carpecodeum** [comment]
@UdeshUK @Tushar19varshney I have made the corresponding changes. Please review now.

**Comment by carpecodeum** [comment]
@ivantha please review

**Comment by carpecodeum** [comment]
@Tushar19varshney As we are moving the backend to flask do you think this is required?

**Comment by ivantha** [comment]
@carpecodeum We don't need it now. But we can merge if you fix the issues in this and keep the node server as a legacy version.

**Pull request merged**
