### PR TITLE
Create layout for classifier model editor

### PR DESCRIPTION
**Pull request by laksh22**
# Description

The basic layout of the classifier model editor has been added. Additionally, the `<ModelEditor />` component is extensible as it renders the type of editor based on the URL params.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Clicked on the __Create New Model__ button which opened up the model editor.

**Test Configuration**:
Layout of the model editor:
modeleditor

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ivantha** [comment]
Hi @laksh22, 
Can you please update some more designs on how this component is going to turn out after all the changes?

**Comment by laksh22** [comment]
@ivantha Sure, I have added the new mockups to issue #425. You can find it under the _See UI mockups_ section

**Comment by laksh22** [comment]
@ivantha Are the UI mockups alright?

**Comment by ivantha** [comment]
> @ivantha Are the UI mockups alright?

Yes they are. I am sorry about the delay in reviewing this 🙂

**Pull request merged**
