### PR TITLE
Password hash

### PR DESCRIPTION
**Pull request by carpecodeum**
# Description
includes bcryptjs to hash the password before saving the password
Fixes # (issue) 122

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] checked by observing the changes in the database

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by carpecodeum** [comment]
sorry this fixes issue no 121

**Comment by carpecodeum** [comment]
hey sorry to have a little confusion here but i had proposed these changes 2 days back only just didn't have the time to push the branch as i was travelling :) and yes i have also installed bcryptjs. Thanks for bringing this to my attention but as you can see your code has saved newuser object while it should be newUser.
not trying to step on anyones toes :) i hope this resolves any confusions.

**Comment by Rupeshiya** [comment]
Great! @carpecodeum. Go ahead and contribute as much as you can. Just follow those steps , it will help you.
Happy coding!

**Comment by carpecodeum** [comment]
there already exits a bcrypt hash generation

**Comment by Rupeshiya** [comment]
Sorry @carpecodeum , I didn't get you. Can you please point me to the codebase where password hashing is done, when user is registering.

**Comment by carpecodeum** [comment]
@Rupeshiya under the user model

**Comment by Rupeshiya** [comment]
Yeah, got that.
Thanks @carpecodeum

**Pull request closed without merging**
