### PR TITLE
Update project details screen UI

### LINKED ISSUE #358: UI Update on project details screen
**Is your feature request related to a problem? Please describe.**
I think the current UI of the project screen can be beautified by adding an image as the sliver background.

**Describe the solution you'd like**
Since there is no project image property specified yet, we can use a random image from the project images.

**Additional context**
I would like to work on this update.

### PR DESCRIPTION
**Pull request by cazci**
# Description

Updated the project details screen. Set a random image from the project images as the background of the sliver appbar. Please refer to the screenshot to get a better idea. 

Fixes #358 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Screenshots

Screenshot_1584126565

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by UdeshUK** [comment]
Can you integrate multiple images(4 images)?

**Comment by cazci** [comment]
Can you please elaborate a bit more. You mean like a grid or a carousel?

**Comment by UdeshUK** [comment]
Grid with 4 recent images?

**Comment by cazci** [comment]
I've updated the cover to a row with a maximum of 4 images. I chose a row over gird as a grid may have inconsistencies when the total image count is less than 4.

### Updated UI
Screenshot_1590115100

**Pull request merged**
