### PR TITLE
Image size warnings

### LINKED ISSUE #129: there is no warning coming for the minimum size of the image to be uplaoded
**Describe the bug**
there is no warning coming for the minmum size of the image that can be uploaded

**To Reproduce**
1. Go to 'create a new project or go to an existing one.'
2. Click on 'project images'
3. Scroll down to 'select an image of size greater than 150 kb and try submitting it'

**Expected behavior**
there should have been a warning displayed that the size of the image to be uploaded is too large

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac Os catalina
 - Browser [e.g. chrome, safari] chrome

**Additional context**
working on it!

### PR DESCRIPTION
**Pull request by carpecodeum**
# Description

added a detailed warning to allow users to check the size of the images they are uploading before uploading.

Fixes #129

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] this was tested by uploading different sized images both graeter and lesser than 101kb

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by carpecodeum** [comment]
@Tushar19varshney please review

**Comment by Tushar19varshney** [comment]
Rebase your branch!

**Comment by carpecodeum** [comment]
@Tushar19varshney please review

**Comment by carpecodeum** [comment]
@ivantha @Tushar19varshney please review

**Comment by carpecodeum** [comment]
@ivantha please review

**Comment by carpecodeum** [comment]
closing this pr as it is outdated and the updated one is #331

**Pull request closed without merging**
