### PR TITLE
Upload directory of images

### LINKED ISSUE #272: Directory upload
**Is your feature request related to a problem? Please describe.**
While annotating an image dataset for object detection tasks, uploading every image manually is very tedious. This feature will allow the user to upload an entire `directory of images`. 

**Describe the solution you'd like**
Provide the user with an option to upload the directory of images.

**Describe alternatives you've considered**
NA

**Additional context**
Currently working on this feature.

### PR DESCRIPTION
**Pull request by 2knal**
# Description

We can now add directory containing the images we want to upload.
They'll be added to the server's `uploads/<directory_name>` directory.

Fixes #272

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

On the forked repo.

Also, include screenshots of app for the verification and reviewing purpose.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by 2knal** [comment]
@Tushar19varshney, right now I've just displayed the directory name in front of the image. Can you please suggest a better UI representation for the same?

**Comment by Tushar19varshney** [comment]
> @Tushar19varshney, right now I've just displayed the directory name in front of the image. Can you please suggest a better UI representation for the same?

Current UI is sufficient for implementing this feature.
@2knal Why that image link thing coming when you are uploading a directory as a directory can contain many images ??

**Comment by Tushar19varshney** [comment]
Also, rebase your PR!

**Comment by 2knal** [comment]
> Current UI is sufficient for implementing this feature.
> @2knal Why that image link thing coming when you are uploading a directory as a directory can contain many images ??

Sorry, can you please elaborate, I didn't understand what you meant by that. 🙈

**Comment by UdeshUK** [comment]
Closing because of inactivity

**Pull request closed without merging**
