### PR TITLE
Feature/object detection

### PR DESCRIPTION
**Pull request by ShreyAmbesh**
# Description

The app was having the option to only send a classification request to the backend and display the results but nothing for object detection.
I have made a mock endpoint for object detection and the full implementation of sending an object detection request and displaying them in the history section.
The history Section has a toggle on the top right to move between classification and object detection results.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

I have tested by making object detection as well as classification requests.

- [x] Making Object Detection request.
- [x] Making Classification request.

**Test Configuration**:

- Firmware version: Flutter 1.12.13+hotfix.8
- Hardware:
- Toolchain:
- SDK: 28

Also, include screenshots of app for the verification and reviewing purpose.
photo_2020-03-31_22-18-33
photo_2020-03-31_22-18-35
photo_2020-03-31_22-18-39

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Tushar19varshney** [comment]
@ShreyAmbesh Can you resolve the codacy quality check?

**Comment by ivantha** [comment]
This will be properly implemented through GSoC 2020 objectives.

**Comment by ivantha** [comment]
@cazci Can you use this?

**Comment by cazci** [comment]
Yes @ivantha, I guess we can combine the two features and show object coordinates by default. Wdyt @UdeshUK

**Comment by UdeshUK** [comment]
@ivantha @cazci the question is whether we support object detection in your ML models or just classifications? But anyway we can present both classifications and object detections on the same history list without having to toggle between screens

**Pull request closed without merging**
