### PR TITLE
Add "on the fly" edit option

### LINKED ISSUE #249: Edit Label option
**Is your feature request related to a problem? Please describe.**
While labeling images, we may feel the need for editing a few labels. However, in the current scenario, we have to go back to the `Project Labels` panel, delete that label, create a new one with the updated value.
This feature will reduce the hassle of moving back and forth for editing a certain label.

**Describe the solution you'd like**
On the fly edit option while labeling images and in the `Project Labels` panel.

**Describe alternatives you've considered**
NA

**Additional context**
Currently working on it.

### PR DESCRIPTION
**Pull request by 2knal**
# Description

Added edit option for labels in `Project labels` pane.
Added a modal in `image labeller` pane, to edit labels on the fly.

Closes #249

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

On forked repo.
<br>
image
image
image

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by carpecodeum** [comment]
@2knal I dont think this feature is required as we already have an update label option.

**Comment by 2knal** [comment]
Yes @carpecodeum, I totally get your point.
However, the main reason for implementing this issue is to reduce the number of steps required to update a label, as currently its quite tedious to go back to the menu, update the label and again go back to the image labeller option. 
Also, I've implemented this feature after getting a heads-up on the group. I hope you understand.
Thanks :)

**Comment by carpecodeum** [comment]
> Yes @carpecodeum, I totally get your point.
> However, the main reason for implementing this issue is to reduce the number of steps required to update a label, as currently its quite tedious to go back to the menu, update the label and again go back to the image labeller option.
> Also, I've implemented this feature after getting a heads-up on the group. I hope you understand.
> Thanks :)

As far as the procedure for updating label goes its pretty straightforward as of now. We can edit the labels directly from the list of labels and click on the update label option. 
It's a good fix undoubtedly well done 👍! 
Also I would recommend you to squash your commits and use rebase.
Happy coding!

**Comment by 2knal** [comment]
Yes @carpecodeum, 
I'll make the necessary changes.
Thanks! 😊

**Comment by UdeshUK** [comment]
Closing because of inactivity

**Pull request closed without merging**
