### PR TITLE
Restoring the App Theme 

### PR DESCRIPTION
**Pull request by M-A-D-A-R-A**
# Description
After Upgrading the mobile application to version 3.0, there were some theme changes we noticed, this PR is to Restore those changes.

##Video Recording(after upgrading to v3.0)

https://user-images.githubusercontent.com/56160262/176645771-286b6535-b4ec-433d-a8bd-13eac86f5622.mp4

##Video Recording(after making changes in v3.0)

https://user-images.githubusercontent.com/56160262/176745250-894b11c0-354f-4946-a4a9-a6706c2e967f.mp4

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Test Configuration**:

- Firmware version: Windows
- Hardware: SM M426B
- SDK: Flutter SDK (v 3.0.2)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by amlannandy** [comment]
@M-A-D-A-R-A Please add screenshots of all the affected screens

**Comment by M-A-D-A-R-A** [comment]
> @M-A-D-A-R-A Please add screenshots of all the affected screens

Added the ScreenRecoding before and after.

**Comment by amlannandy** [comment]
@M-A-D-A-R-A Few changes that are still required -
1. Profile Screen had a white-colored navbar.
2. Team Details Screen also had a white-colored navbar.
3. The back arrow is not visible in any of the white navbars as they're still white-colored. Changed them to a darker gray/black variant as it was before.
4. Add recording for ALL screens. Check the mobile screenshots section in Wiki for reference.

**Comment by M-A-D-A-R-A** [comment]
> @M-A-D-A-R-A Few changes that are still required -
> 
> 1. Profile Screen had a white-colored navbar.
> 2. Team Details Screen also had a white-colored navbar.
> 3. The back arrow is not visible in any of the white navbars as they're still white-colored. Change them to a darker gray/black variant as it was before.
> 4. Add recording for ALL screens. Check the mobile screenshots section in Wiki for reference.

@amlannandy made changes please review.

**Review by amlannandy — APPROVED** [review]
Looks great! Thanks for the changes! 🎉

**Pull request merged**
