### PR TITLE
Fixed the Error [ERR_HTTP_HEADERS_SENT]

### PR DESCRIPTION
**Pull request by ShreyAmbesh**
# Description
Fixed the error Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client 
It used to come when a request was made to an endpoint which doesn't exist

Screenshot from 2020-03-31 00-19-27

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
- [x] Tested by making request to an endpoint which doesn't exist

**Test Configuration**:

- Firmware version: Flutter 1.12.13+hotfix.8
- Hardware:
- Toolchain:
- SDK: 28

Also, include screenshots of app for the verification and reviewing purpose.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Tushar19varshney** [comment]
@ShreyAmbesh Checks are failing, can you update you PR with the necessary changes?

**Comment by ivantha** [comment]
> @ShreyAmbesh Checks are failing, can you update you PR with the necessary changes?

@Tushar19varshney Shall we get this merged for now and do a code cleanup at the end of the GSoC?

**Comment by Tushar19varshney** [comment]
> > @ShreyAmbesh Checks are failing, can you update you PR with the necessary changes?
> 
> @Tushar19varshney Shall we get this merged for now and do a code cleanup at the end of the GSoC?

I don't think this error is causing any problem right now and also I don't see this piece of code solving this error. We can put this PR on hold till we need this badly. What say?

**Comment by UdeshUK** [comment]
Closing since there are conflicts and the purposed fix calls an undefined method producing a runtime error.

**Pull request closed without merging**
