### PR TITLE
Mobile Implementation:  Implement the screens for displaying all issues

### PR DESCRIPTION
**Pull request by M-A-D-A-R-A**
# Description
Implemented issues listing screen within the project. (Mobile Frontend)
(Work in Progress)

https://user-images.githubusercontent.com/56160262/178544261-9632e619-911c-4431-af84-bea17d396452.mp4

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

*Test Configuration*:

- Firmware version: Windows
- Hardware: SM M426B
- SDK: Flutter SDK (v 3.0.2)

Also, include screenshots of the app for verification and reviewing purposes.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by M-A-D-A-R-A** [comment]
@amlannandy Fetching and Creating issues have been done till the last commit. Please review

**Comment by amlannandy** [comment]
@M-A-D-A-R-A Add a recording of both the functionalities. Also, does this include filtering?

**Comment by M-A-D-A-R-A** [comment]
> @M-A-D-A-R-A Add a recording of both the functionalities. Also, does this include filtering?

Sorry, I forgot to update the comment.
Filtering is not yet included will do that in the following PR including updating the issue.
I will work on the UI after all the significant functions / API endpoints are made. will that be okay?

**Comment by amlannandy** [comment]
@M-A-D-A-R-A Also do create a separate ticket for UI improvements

**Pull request merged**
