### PR TITLE
Fix errors in mobile app

### LINKED ISSUE #524: Compiliation Errors in Mobile App
**Describe the bug**

1.  The fluro package used for routing changed the name of its Router class from 'Router' to 'FluroRouter' due to which the Router class was undefined in code.
2. Some functions in repository.dart file were commented out but still being used.

**To Reproduce**
All Errors are visible automatically in terminal when you open the project folder

**Smartphone (please complete the following information):**
 - Device: Realme 3 Pro

**Additional context**

### PR DESCRIPTION
**Pull request by amlannandy**
# Description

1. For fixing the issue related to fluro packages, I renamed all reference of Router class to FluroRouter.
2. Uncommented missing functions.

Fixes #524 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

No errors are now shown in the terminal and App can be run.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by amlannandy** [comment]
For point no, 2, can any of the project maintainers please tell if it's okay to just uncomment the missing code or is another fix necessary, assuming the code was originally commented out for some reason?

**Comment by cazci** [comment]
Thanks for the PR @amlannandy. 

The code was initially commented due to an issue with the provider package, and if there are no issues with the build it's fine to uncomment it. The rest looks good to me.

**Comment by amlannandy** [comment]
> Thanks for the PR @amlannandy.
> 
> The code was initially commented due to an issue with the provider package, and if there are no issues with the build it's fine to uncomment it. The rest looks good to me.

Actually the app build was still failing. I had to update the gradle distribution url in another commit and now the app is working. 👍🏻

**Review by UdeshUK — APPROVED** [review]
Nice work 👍🏻

**Pull request merged**
