### PR TITLE
Add image export option

### LINKED ISSUE #298: Image export option
**Is your feature request related to a problem? Please describe.**
After labeling the uploaded dataset, the next step is to export it in particular formats so that we can use it for image classification or object detection/segmentation.

**Describe the solution you'd like**
Providing an option to export the labeled dataset in `Pascal VOC`, `YOLO`  or `JSON` data format.

**Describe alternatives you've considered**
NA.

**Additional context**
Would love to work on it!

### PR DESCRIPTION
**Pull request by 2knal**
# Description

Added a button, with which we can create annotation files for all uploaded images.
These annotations also get downloaded as `annotations.zip`.
The downloaded annotations can further be used for any custom object detection models.
> Dependency change:
> - archiverjs
> - xmlbuilderjs

Closes #298 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

On local forked repository.
image
image
image
image

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Tushar19varshney** [comment]
Rebase the PR!

**Comment by 2knal** [comment]
> Rebase the PR!

Sorry,
I have made the necessary changes, please have a look.

**Comment by Tushar19varshney** [comment]
@2knal Could you please rebase it again ? Also, check the codacy errors as it was failing.

**Comment by 2knal** [comment]
> @2knal Could you please rebase it again ? Also, check the codacy errors as it was failing.

Is it alright now? <br> Sorry for the delayed response.

**Comment by UdeshUK** [comment]
Close because of the inactivity

**Pull request closed without merging**
