### PR TITLE
Standardize button colors based on their functionality

### LINKED ISSUE #405: Make button colors uniform based on functionality
**Describe the bug**
Most of the buttons in the client perform 3 functions: Addition, Deletion, and Editing. In the current implementation, the buttons do not have a uniform color scheme. It would be better for the user experience if buttons were colored consistently based on their functionality.

**To Reproduce**
1. Create a new project
2. Open the __Project Team__ tab and notice the color of the __Add member__ button is `00a89f`
3. Open the __Project Images__ tab and notice the color of the __Add Image__ button is blue

**Expected behavior**
The buttons should be colored based on their functionality in a consistent manner:
> Addition - `positive`
> Deletion - `negative`
> Editing - default

**Screenshots**
Add member, Add Image, and Add Label, all of different colours:

**Additional context**
Working on it

### PR DESCRIPTION
**Pull request by laksh22**
# Description

Earlier, buttons were mostly colored arbitrarily and did not follow a color scheme. This has been changed as follows:
> Addition - positive
Deletion - negative
Editing - default

Fixes #405  (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Each page of the application was opened to see if the buttons on the page followed the style rules.

**Test Configuration**:

Some examples:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Tushar19varshney** [comment]
@laksh22 Your thinking regarding standarization is correct but I think it is not looking very pleasant. I think we need to discuss some UI fixes regarding this.

**Comment by laksh22** [comment]
Yeah I think the buttons are too bright. We could use outline buttons with the same colours instead of buttons with filled colours

**Comment by ivantha** [comment]
@Tushar19varshney @laksh22 Can we get the necessary fixes done and get this merged? 🙂

**Comment by laksh22** [comment]
@ivantha @Tushar19varshney Are the images attached in the comments of issue #406 alright? If yes than I'll add those changes

**Comment by Tushar19varshney** [comment]
@laksh22 I think instead of making background red you can make font color red, that will be much better than the present one.

**Comment by laksh22** [comment]
@Tushar19varshney The latest version:
buttons

**Comment by Tushar19varshney** [comment]
> @Tushar19varshney The latest version:
> buttons

It looks better than the last iteration :+1:

**Comment by Tushar19varshney** [comment]
@laksh22 Standardize the same scheme to the whole project, then we are ready to merge this PR.

**Comment by laksh22** [comment]
@Tushar19varshney The buttons should appear the same in all places now:
btn2
btn3
btn1

**Comment by ivantha** [comment]
Nice work! :+1:

**Pull request merged**
